### ISSUE TITLE
[ Feature ] - 팀 관련 API (팀 생성, 팀 참여하기, 팀 나가기)

### ISSUE THREAD

**Issue by leeeunda** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_23_BE#10]
## 🛠️ 개발 예정 기능
팀 생성 API
팀 참여하기 API
팀 나가기 API

## 💭 해당 기능 역할
팀 이름, 카테고리, 모집 인원, 밤샘 시간, 비밀방 여부, 팀 소개 문구를 받아 팀 생성 모집글을 작성하고 유저가 모집글을 통해 모집글을 조회하고 팀 가입하기 버튼을 눌러 팀에 가입한다. 팀 나가기 버튼을 누르면 팀에서 나간다.

### 📝 check-lists

- [x] 팀 생성 API
- [x] 밤샘 팀 가입하기 API
- [x] 팀 나가기 API
- [x] 유저는 하나에 팀에만 가입하도록 처리
- [x] 팀 인원 제한이 넘으면 가입할 수 없음
- [x] 유저가 팀에 참여시 팀 인원을 변경
- [x] 팀을 생성한 경우 방장 활성화, 자동으로 팀 인원 1 증가

**Comment by dongkyeomjang** [comment]
고생하셨습니당
